source 'https://rubygems.org'
source ENV['HYPER_DEV_GEM_SOURCE'] if ENV['HYPER_DEV_GEM_SOURCE']
gem "sinatra"
gem "opal-d3", path: ".."
gem "opal-sprockets"
gem "opal-jquery", git: "https://github.com/opal/opal-jquery.git", branch: "master"
gem "hyper-component", "~> 1.0.0.lap23"